BOOTMAGIC_ENABLE    = yes
SECURE_ENABLE       = yes
LEADER_ENABLE       = yes
CAPS_WORD_ENABLE    = yes
AUTO_SHIFT_ENABLE   = yes
MOUSEKEY_ENABLE     = yes
OS_DETECTION_ENABLE = yes
LTO_ENABLE          = yes
