name: Build QMK Firmware - docker

on:
  push:
    branches:
    - Keychron-Q1

jobs:
  build_in_docker:
    name: Use QMK Docker image
    runs-on: ubuntu-latest
    steps:
    - name: Check out Repo
      uses: actions/checkout@v3

    - name: Build Firmware
      run: util/docker_build.sh keychron/q1/ansi:bugstop

    - name: Rename Output
      run: |
        echo "ymd=$(date '+%Y%m%d')" >> $GITHUB_ENV
        cp keychron_q1_ansi_bugstop.hex qmk_keychron_q1_$(date '+%Y%m%d')_ubuntu.hex

    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: qmk-ubuntu-build-result-keychron-q1-${{ env.ymd }}
        path: qmk_keychron_q1_${{ env.ymd }}_ubuntu.hex
        retention-days: 90
