name: Build QMK Firmware - docker

on:
  push:
    branches:
    - Keychron-Q1Pro

jobs:
  build_in_docker:
    name: Use QMK Docker image
    runs-on: ubuntu-latest
    steps:
    - name: Check out Repo
      uses: actions/checkout@v4

    - name: Build Firmware
      run: util/docker_build.sh keychron/q1_pro/ansi_knob:customized

    - name: Rename Output
      run: |
        echo "ymd=$(date '+%Y%m%d')" >> $GITHUB_ENV
        cp keychron_q1_pro_ansi_knob_customized.bin qmk_keychron_q1pro_$(date '+%Y%m%d')_ubuntu.bin

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: qmk-ubuntu-build-result-keychron-q1pro-${{ env.ymd }}
        path: qmk_keychron_q1pro_${{ env.ymd }}_ubuntu.bin
        retention-days: 90
