name: Build QMK Firmware

on:
  push:
    branches:
    - master

jobs:
  build_in_docker:
    name: Use QMK Docker image
    runs-on: ubuntu-latest
    steps:
    - name: Check out Repo
      uses: actions/checkout@v3

    - name: Build Firmware
      run: util/docker_build.sh keychron/q1/ansi:via

    - name: Rename Output
      run: |
        echo "ymd=$(date '+%Y%m%d')" >> $GITHUB_ENV
        cp keychron_q1_ansi_via.hex qmk_keychron_q1_via_$(date '+%Y%m%d')_ubuntu.hex

    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: qmk-ubuntu-build-result-keychron-q1-${{ env.ymd }}
        path: qmk_keychron_q1_via_${{ env.ymd }}_ubuntu.hex
        retention-days: 90

  build_on_macos:
    name: Setup QMK env on macOS
    runs-on: macos-latest

    steps:
    - name: Check out Repo
      uses: actions/checkout@v3

    - name: Set Upstream
      run: |
        echo `date`
        git remote add upstream https://github.com/qmk/qmk_firmware.git
        git remote -v

    - name: Update Submodules
      run:  git submodule update --init --recursive

    - name: Install Homebrew
      run: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

    - name: QMK Installation
      run: brew install qmk/qmk/qmk

    - name: QMK Installation Patch
      run: |
        brew tap ArmMbed/homebrew-formulae
        brew install avr-gcc
        brew install arm-none-eabi-gcc
        make lets_split-rev2-default-avrdude

    - name: Run QMK Setup
      run: qmk setup

    - name: Build Firmware
      run: qmk compile -kb keychron/q1/ansi -km via

    - name: Rename Output
      run: |
        echo "ymd=$(date '+%Y%m%d')" >> $GITHUB_ENV
        cp keychron_q1_ansi_via.hex qmk_keychron_q1_via_$(date '+%Y%m%d')_macos.hex

    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: qmk-macos-build-result-keychron-q1-${{ env.ymd }}
        path: qmk_keychron_q1_via_${{ env.ymd }}_macos.hex
        retention-days: 90
